/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Upgrades": "升级",
    "Feature": "功能",
    "As the voice fades away, you look at your own hands, and see ten points manifest as rings. One for each finger.": "当声音渐渐消失，你看着自己的双手，看到十个点变成了圆环。每个手指一个。",
    "celestial points per second.": "天体点数每秒。",
    "celestial points.": "天体点数。",
    "Gwagwagwa.": "Gwagwagwa。",
    "It seems as if it's always night. The stars stand in place.": "似乎永远都是黑夜。星星站在原地。",
    "The wind is moderate. It is quite cold.": "风不大。天气很冷。",
    "Universe 1 - Overworld": "宇宙1 -上界",
    "Unlocks Ranks.": "解锁等级。",
    "You are gaining": "你获得",
    "You find yourself in a vast desert of black sand.": "你发现自己身处一片广袤的黑沙沙漠。",
    "You hear a voice in the distance. \"This place is dead. Bring it back to life and know your purpose.\"": "你听到远处有声音。“这地方死气沉沉。让它起死回生，明白你的目的。”",
    "Toggle Hotkeys": "切换快捷键",
    "Toggle Music": "切换音乐",
    "Change Theme": "更改主体",
    "Autosave": "自动保存",
    "Changelog:": "更新日志:",
    "Credits:": "鸣谢:",
    "Hotkeys:": "快捷键:",
    "Join the Discord!": "加入 Discord!",
    "Offline Prod": "离线生产",
    "Features": "功能",
    "Unlocks Factors.": "解锁因子。",
    "Unlocks Tetr (In ranks).": "解锁Tetr（按等级）。",
    "You are at rank": "你当前是等级",
    "You are at tier": "你当前是层级",
    "Return": "返回",
    "Ranks": "等级",
    "Main": "主界面",
    "Factors": "因子",
    "Factor": "因子",
    "Reset celestial points and ranks, but tier up.": "重置天体点数和等级，但层级会更高。",
    "Reset celestial points, but rank up.": "重置天体点数，但等级会更高。",
    "Power Factors": "力量因子",
    "Prestige": "声望",
    "Unlocks Power Factors (In factors).": "解锁力量因子 (按因子).",
    "Unlocks Prestige.": "解锁声望。",
    "Autobuys factors I-VIII.": "总共购买 因子 I-VIII.",
    "Autobuyers don't spend resources. This applies to most autobuyers in the game.": "自动购买者不消耗资源。这适用于游戏中的大多数自动购买者。",
    "Boosts celestial points based on prestige points.": "根据声望点数提升天体点数。",
    "prestige points on reset.": "声望点数当重置时。",
    "prestige points.": "声望点数。",
    "Prestige Upgrade": "声望升级",
    "Prestige, but reset all ranks and factors.": "声望，但重置所有等级和因子。",
    "Triples celestial point gain.": "三倍天体点数增益。",
    "You will gain": "你将获得",
    "You can buy max ranks, tiers, tetr, etc.": "你可以购买最大等级，层级，tetr等等。",
    "Reset celestial points ranks and tier, but tetr up.": "重置天体点数的等级和层级，但tetr会更高。",
    "You are at tetr": "你当前在tetr",
    "(softcapped)": "(已达软上限)",
    "Trees": "树",
    "Tree": "树",
    "Grass": "草",
    "Unlocks Grass.": "解锁草.",
    "Unlocks Trees.": "解锁树.",
    "Leaf Multiplier": "树叶乘数",
    "Leaf Producer": "树叶产生器",
    "leaves per second.": "树叶每秒。",
    "Leaves to gain a tree.": "树叶获得一棵树。",
    "Requirement Divider": "需求除法器",
    "Softcap Extender": "软上限扩展器",
    "Tetr boosts factor power gain.": "Tetr 提升因子力量增益。",
    "trees.": "树.",
    "Power": "力量",
    "Power Factor": "力量因子",
    "Autobuy grass and prestige upgrades.": "自动购买草和声望升级。",
    "Autobuy tree buyables and unlocks grasshop.": "自动购买树的可购买并解锁草地。",
    "Autobuys grass buyables, and unlocks tree factor VI.": "自动购买草可购买，并解锁 树因子VI。",
    "Next factor unlocks at Prestige Upgrade XII.": "下一个因子解锁于声望升级 XII。",
    "Tree Factor": "树因子",
    "Reset all content before grass, but pent.": "重置所有内容之前的草，除了pent。",
    "Unlock mods (in trees).": "解锁模组 (按树).",
    "Unlock tree factor VIII and autobuy tree and grass factors.": "解锁树因子VIII和自动购买树和草因子",
    "Unlocks a new type of factor and grass upgrades.": "解锁一种新的因子和草升级。",
    "Unlocks Tree Factor IV.": "解锁树因子IV。",
    "You are at pent": "你在pent",
    "Boost tree gain based on grass.": "提高树增益基于草。",
    "Boosts grass value based on prestige points.": "根据声望点提升草的价值。",
    "Buyables": "可购买",
    "Golden Grass": "金草",
    "Grass Capacity": "草容量",
    "Golden Grass Capacity": "金草容量",
    "Grass Upgrade": "草升级",
    "Grass Value": "草价值",
    "Golden Grass Value": "金草价值",
    "golden grass.": "金草。",
    "Grass Prestige Point Boost": "草声望点数提升",
    "Grass Celestial Point Boost": "草天体点数提升",
    "Grass Grow Rate": "草生长率",
    "Grass Factor Power Boost": "草因子力量提升",
    "grass, which boost leaf gain by": "草，提升树叶增益",
    "Pent Requirement Divider": "Pent需求除法器",
    "Unlocks Golden Grass.": "解锁金草。",
    "Unlocks golden grass buyables.": "解锁金草可购买。",
    "Unlocks more tree buyables.": "解锁更多树可购买。",
    "golden grass, which boost grass value by": "金草，这提高了草的价值",
    "Autobuys power factors I-VIII": "自动购买力量因子 I-VIII",
    "Automates rank gain.": "自动化等级增益。",
    "Automates tetr gain.": "自动化tetr增益。",
    "Automates tier gain.": "自动化层级增益。",
    "Prestige Upgrade": "声望升级",
    "Unlocks Power Factor VIII, and more tree buyables.": "解锁力量因子VIII，和更多树可购买。",
    "Celestial Point Booster": "天体点数助推器",
    "Factor Power Booster": "因子力量助推器",
    "Grass Value Booster": "草价值助推器",
    "Golden Grass Value Booster": "金草价值助推器",
    "Effects": "效果",
    "Tree Study": "树研究",
    "Grass Study": "草研究",
    "Factor Study": "因子研究",
    "fertilizer per second.": "肥料每秒。",
    "grasshoppers.": "蚱蜢。",
    "Grasshop": "草地",
    "Grasshop, but reset everything except pent.": "草地，但重置了所有的东西，除了pent。",
    "Next factor unlocks at Grass Upgrade VII.": "下一个因子解锁于 草升级 VII。",
    "Prestige Study": "声望研究",
    "Upgrade Tree": "升级树",
    "Unlocks tree factor V.": "解锁树因子 V.",
    "Check Back": "回访",
    "The Temple of Gwa": "Gwa庙",
    "Unlocks Check Back.": "解锁回访。",
    "Unlocks Pent (in ranks).": "解锁Pent (按等级).",
    "Next factor unlocks at 20 mods.": "下一个因子解锁于 20 模组。",
    "grasshoppers on reset.": "蚱蜢在重置时。",
    "Factors unlock with Grass Study III.": "因子解锁于 草 研究III",
    "Grass Factor": "草因子",
    "Code Experience": "代码经验",
    "Code Experience Multiplier": "代码经验乘数",
    "Golden Grass Value Multiplier": "金草价值乘数",
    "mods.": "模组.",
    "Mods": "模组",
    "Point, Factor Power, and Prestige Point Multiplier": "点数、因子力量和声望点数乘数",
    "Reset everything except grasshop and pent for code experience.": "重置所有东西，除了草地和pent的代码经验。",
    "Lines of code to make a mod.": "行代码用以制作模组。",
    "lines of code per second. (Based on code experience)": "代码行数每秒。（基于代码经验）",
    "Lines of Code Multiplier": "代码行乘数",
    "code experience on reset.": "代码经验在重置时。",
    "Mod Study": "模组研究",
    "Portal": "传送门",
    "Unlocks The Portal.": "解锁传送门。",
    "\tContent:": "\t内容:",
    "\tBalancing:": "\t平衡:",
    "\tBugfixes:": "\t改错:",
    "\tQoL:": "\t生活质量:",
    "Unlocks a new check back button.": "解锁一个新的回访按钮。",
    "Unlocks new grasshop studies.": "解锁新的蚱蜢研究。",
    "YOU MUST REACH 1e100 POINTS TO ACTIVATE CHECK BACK AND PET EFFECT": "你必须达到1e100点才能激活回访和宠物效果",
    "Collect a random common pet.": "随机收集一只普通宠物。",
    "Common": "普通",
    "Collect a random uncommon/common pet.": "随机收集一个罕见/普通宠物。",
    "Current Evolutions": "当前进化",
    "Evolution": "进化",
    "evolution shards.": "进化碎片。",
    "EVOLVE": "进化",
    "Shark": "鲨鱼",
    "Unsmith": "非铁匠",
    "Level Up": "升级",
    "Open Shop": "打开商店",
    "pet points.": "宠物点数。",
    "Pets": "宠物",
    "Rare": "稀有",
    "Rare Pets": "稀有宠物",
    "Uncommon": "罕见",
    "View Evolutions": "查看进化",
    "XP": "经验值",
    "XP to level up.": "经验值以升级。",
    "(Gained from check back buttons)": "（从回访按钮获得）",
    "Buy Pet": "购买宠物",
    "Check back in": "回访时间还有",
    "Miscellaneous": "杂项",
    "Reset Shop Prices": "重置商店价格",
    "Next": "下一个",
    "You gained an Egg Guy!": "你得到了一个鸡蛋男！",
    "Common Pets": "普通宠物",
    "Uncommon Pets": "罕见宠物",
    "You gained an Unsmith!": "你获得了一个非铁匠！",
    "You gained THE WATCHING EYE!": "你获得了监视之眼！",
    "You gained a Gd Checkpoint!": "你获得了一个Gd检查点！",
    "You gained a Shark!": "你得到了一条鲨鱼！",
    "You gained a Star!": "你获得了一颗星星！",
    "You gained a Normal Face!": "你获得了一个普通脸！",
    "Collect a random uncommon pet.": "随机收集一只罕见的宠物",
    "Boosts mod gain based on check back level.": "提高模组增益基于回访等级。",
    "Check Back Study": "回访研究",
    "\"Do not worry about the second value; it will reveal its purpose when you leave this place.\"": "“不要担心第二个值；当你离开这个地方时，它就会显示出它的用途。”",
    "A dot manifests itself in the center of your vision.": "一个点出现在你视野的中心。",
    "A purple, tall humanoid figure greets you with your name.": "一个紫色、高大的人形人物用你的名字向你打招呼。",
    "As you walk through the unfamiliar landscape. A very colorful land with a flat, smooth ground.": "当你走过陌生的风景。那是一片色彩斑斓的土地，地面平坦光滑。",
    "Dice": "骰子",
    "Fly me to the moon.": "带我飞向月球。",
    "free feature slots.": "免费功能插槽。",
    "Otherworldly Features": "超凡脱俗的功能",
    "Portals": "传送门",
    "Rocket Fuel": "火箭燃料",
    "The aspect of randomness entices you, so you select the number.": "随机性吸引着你，所以你选择了数字。",
    "The die will decide your fate.": "骰子将决定你的命运。",
    "The edges shake and rapidly flicker, signaling the portal is clearly unstable. You don't plan on missing this opportunity.": "边缘抖动并快速闪烁，表明传送门明显不稳定。你不会错过这个机会的。",
    "The humanoid figure nods, and he points what appears to be a finger towards you; the numbers you select are now imbued into your knowledge.": "人形点点头，用一根手指指着你；你选择的数字现在已经融入了你的知识。",
    "The second value seems to be blank, not returning any meaningful value.": "第二个值似乎是空白的，没有返回任何有意义的值。",
    "This dot slowly grows into a ring, with a purple-blue gradient slowly fading into view.": "这个点慢慢地成长为一个环，紫蓝色的渐变慢慢地消失在视野中。",
    "When you walk through, your brain immediately floods with information; the SPVs in the space the portal brought you to constantly rise, fall, and transform.": "当你走过的时候，你的大脑会立即被信息淹没；在传送门带给你的空间里的spv不断地上升、下降和转变。",
    "You observe two numbers: the first value randomly selects a number between 1 and 6.": "观察两个数字：第一个值随机选择1到6之间的一个数字。",
    "\t(They only bring you to the selected universe if you have it unlocked)": "\t（他们只带你到选定的宇宙，如果你有它解锁）",
    "\tA - Alt-Universe 1.": "\tA - Alt-宇宙 1.",
    "\tQ - Universe 1.": "\tQ - 宇宙 1.",
    "\tW - Universe 2.": "\tQ - 宇宙 2.",
    "5% chance for a pet???": "5%几率获得宠物??？",
    "Autoroll": "自动投掷",
    "Booster Dice": "助推器骰子",
    "Dice Side Boost": "骰子面提升",
    "DP Multiplier": "骰子点数 乘数",
    "Roll to change currency boost!": "投掷以更改当前提升！",
    "Low Roll Removal": "低投掷清除",
    "Roll!": "投掷!",
    "View Effects": "查看效果",
    "You gained a Dice!": "你获得了一个骰子！",
    "1e308 celestial points- impossible.": "1e308 天体点 - 不可能。",
    "BIG CRUNCH": "大坍缩",
    "\"8 trials lie ahead. Complete them, and I will tell you,\" the figure says.\"": "“前方还有8个考验。“完成它们，我就告诉你，”人影说。",
    "\"You have reached a limit. Now you are almost ready to face the celestials,\" the figure says.\"": "“你已经达到了极限。“现在你差不多准备好面对天神了，”人影说。",
    "An orange, glowing number suddenly appears in the corner of your vision.": "一个橙色的发光数字突然出现在你视线的角落里。",
    "Another humanoid figure appears. This time, the color of the humanoid is orange.": "另一个人形出现了。这一次，人形的颜色是橙色。",
    "antimatter per second.": "反物质每秒。",
    "As the amount of Celestial Points in this universe approaches higher and higher numbers, it suddenly stops.": "当这个宇宙中的天体点数越来越多的时候，它突然停止了。",
    "Gain 5% of grass per second.": "每秒获得5%的草。",
    "infinities.": "无限.",
    "Infinity": "无限",
    "infinity points.": "无限点数.",
    "Keep antimatter progress on regular infinity resets.": "常规无限重置时保留反物质进度。",
    "Keep check back unlocked, gain 5% of prestige points per second.": "保留“回访”解锁，每秒获得5%声望点数。",
    "Keeps grass and prestige upgrades on all resets.": "所有重置时保留草地和声望升级。",
    "Keeps pent milestones on infinity.": "无限时保留pent里程碑。",
    "on reset.": "在重置时。",
    "The figure disappears. The orange fades into a vast grassland.": "人影消失了。橙色渐渐消失，变成一片广阔的草原。",
    "The world's color is inverted. Disturbed, you observe the nearest value. \"Antimatter\" is the name of the observed value.": "世界的颜色颠倒了。不安地，你观察最接近的值。“反物质”是观测值的名称。",
    "Unlock challenges.": "解锁挑战。",
    "Unlocks Antimatter Dimensions.": "解锁反物质维度。",
    "You reach out to observe this number, but it seems to have some kind of force that prevents you from reaching it.": "你伸出手去观察这个数字，但它似乎有某种力量阻止你到达它。",
    "You ask what a celestial is.": "你问什么是天体。",
    "Antimatter Dimensions": "反物质维度",
    "AD Upgrade": "反物质维度升级",
    "Antimatter boosts itself.": "反物质自我提升。",
    "Dimensions": "维度",
    "Max All": "全部最大",
    "Progress gets halted at 1e300 antimatter.": "反物质达到1e300时，进度就停止了。",
    "Gives you 10 antimatter. Spend it wisely.": "给你10个反物质。明智地使用。",
    "Unlocks the portal.": "解锁传送门。",
    "You are capped at 6 dimension boosts and 1 galaxy (for now)": "你的上限是 6 维度提升和1个星系（目前）",
    "Boosts 7th dimensions based on completed rocket fuel runs.": "基于完成的火箭燃料运行提升第7维度。",
    "Boosts antimatter based on completed dice runs.": "基于完成的骰子运行提升反物质。",
    "Boosts factor power and prestige points based on infinities.": "基于无限提升因子力量和声望点数。",
    "Boosts factor power based on antimatter.": "基于反物质提升因子力量。",
    "Boosts golden grass gain based on infinities.": "基于无限提升金草增益。",
    "Boosts mod and lines of code gain based on infinities.": "基于无限提升模组和代码行增益。",
    "Boosts tree and leaf gain based on infinities.": "基于无限提升树和树叶增益。",
    "Boosts code experience based on antimatter.": "基于反物质提升代码经验。",
    "Boosts grass based on antimatter.": "基于反物质提升草。",
    "Boosts trees and leaves based on antimatter.": "基于反物质提升树和树叶。",
    "Boosts mods and lines of code based on antimatter.": "基于反物质提升模组和代码行。",
    "Boosts grasshoppers and fertilizer based on antimatter.": "基于反物质提升蚱蜢和肥料。",
    "Increase factor effect base based on antimatter.": "基于反物质增加因子效应基数。",
    "Infinities boost antimatter dimensions.": "无限提升反物质维度。",
    "Universe 2 - Antimatter World": "宇宙2 - 反物质世界",
    "Boosts grasshoppers based on infinity points.": "基于无限点提升蚱蜢。",
    "Challenge": "挑战",
    "Challenges": "挑战",
    "Reward:": "奖励:",
    "Unlock new grass studies.": "解锁新的草研究。",
    "Unlocks more check back content.": "解锁更多回访内容。",
    "You can't pick an otherworldy feature.": "你不能选择一个超凡脱俗的功能。",
    "Abilities": "能力",
    "Choose an amount to allocate into the ability.": "选择一个数量分配给该能力。",
    "Gain 20% of prestige points and grass value per second.": "每秒获得20%的声望点和草价值。",
    "Gain rocket fuel, but reset everything before unlocking check back. (except pent milestones) (Based on grasshoppers) (~1e15 grasshoppers)": "获得火箭燃料，但在解锁前重置一切。（除了里程碑）（基于蚱蜢）（~1e15只蚱蜢）",
    "Keep pent on reset.": "重置时保留pent。",
    "RF Tree Boost": "火箭燃料 树提升",
    "RF Point Boost": "火箭燃料 点数提升",
    "RF Grass Boost": "火箭燃料 草提升",
    "rocket fuel on reset.": "火箭燃料在重置时。",
    "Rocket Fuel Upgrade": "火箭燃料升级",
    "Balancing:": "平衡:",
    "Unlock mods.": "解锁模组。",
    "XPBoost": "经验提升",
    "XPBoost.": "经验提升.",
    "Debuff": "减益",
    "Antimatter Study": "反物质研究",
    "Antimatter Effect Limit Breaker": "反物质效果上限断路器",
    "Antimatter Dimension Limit Breaker": "反物质维度上限断路器",
    "antidebuff points,": "反减益点数，",
    "antidebuff points on reset.": "反减益点数在重置时。",
    "Antidebuff": "反减益",
    "Alternate Ranks": "候补等级",
    "Anonymity": "匿名",
    "Antimatter World": "反物质世界",
    "Break Infinity": "打破无限",
    "Cante, Celestial of Replicanti": "坎特，复制的天体 ",
    "Celestial": "天体",
    "COMING SOON!!!": "敬请期待!!!",
    "Epic Fragmentation": "史诗碎片",
    "Goldsmith": "金匠",
    "Incremental": "增量",
    "Infinity Dimensions": "无限维度",
    "Insane Face": "疯脸",
    "Overworld": "上界",
    "Otherworldly Feature Mastery": "超凡脱俗功能精通",
    "Perks": "特权",
    "Pet Shop": "宠物商店",
    "Pests": "害虫",
    "Singularity": "奇点",
    "Softcap": "软上限",
    "Sun": "太阳",
    "Realm Mods": "领域模组",
    "Oil": "石油",
    "Repli-Grass": "复制草",
    "Repli-Trees": "复制树",
    "Pollinators": "传粉者",
    "Tav, Celestial of Limits": "Tav，天体上限",
    "Tav's Domain": "Tav的领地",
    "Marcel": "马塞尔",
    "oil on reset.": "石油在重置时。",
    "META": "元",
    "Grass-Skip": "草跳",
    "Epic Shops": "史诗商店",
    "Dragon": "龙",
    "Dotknight": "圆点骑士",
    "Evo. Features": "Evo. 功能",
    "replicanti points.": "复制点数。",
    "Reset all content previous content (except grass and grass-skip) for oil. (Based on anonymity)": "重置所有内容之前的内容（除了草和草跳）为油。（基于匿名）",
    "Reset celestial points, ranks, and tiers, but tetr up.": "重置天体点数，等级和层级，但tetr上升。",
    "Your oil boosts repli-trees and extends repli-tree softcap by": "你的石油提升了 复制树 并扩展了 复制树 的软上限",
    "Infinity Factor": "无限因子",
    "Negative Infinity": "负无限",
    "Negative Infinity Factor": "负无限因子",
    "oil.": "石油.",
    "Autobuy universe 1 upgrades.": "自动购买 宇宙1 升级。",
    "Autobuys grass studies and mod buyables.": "自动购买草研究和模组可购买。",
    "Boosts infinity points based on negative infinity points.": "基于负无限点数提升 无限点数。",
    "Boosts infinity points baseed on negative infinity points.": "基于负无限点数提升 无限点数。",
    "Boosts antimatter dimensions based on negative infinity points.": "基于负无限点数提升 反物质维度。",
    "Boosts code experience based on infinity points.": "基于无限点数提升 代码经验。",
    "Boosts dice points and rocket fuel based on infinity points.": "基于无限点数提升 骰子点数和火箭燃料。",
    "Boosts dimension power based on infinity points.": "基于无限点数提升 维度力量。",
    "Boosts negative infinity points baseed on infinity points.": "基于无限点数提升 负无限点数。",
    "CHALLENGE VIII HAS BEEN TERMINATED.": "挑战 VIII 已经终止。",
    "Check back buyables.": "回访可购买。",
    "Check back pet effects are always active.": "回访宠物效果总是激活的。",
    "Dimension Booster": "维度助推器",
    "Dimension Power Booster": "维度力量助推器",
    "Does an XPBoost-equivalent reset, and XP is being constantly drained. When XP reaches 0, you are sent back a level with very little XP. (RECOMMENDED AFTER FIRST XPBOOST)": "做一个与 经验提升 相当的重置，经验值不断被消耗。当经验值达到0时，你将被送回一个只有很少经验值的等级。（建议在第一次使用经验提升后使用）",
    "Gain 10% of grasshoppers and code experience per second.": "每秒获得10%的蚱蜢和代码经验值。",
    "Gain an option to keep OTFs on infinity reset.": "无限重置时获得一个保留otf的选项。",
    "Hex... A feature seemingly coming from thin air. No check back effects either...": "Hex…似乎是凭空出现的功能。也没有回退效果…",
    "Introduces pests, which do bad things to your grass :(": "引入害虫，对你的草造成不良影响：(",
    "IP and AD upgrades are disabled, some IP milestones are disabled, and pent divides point gain, but is necessary to unlock OTFs.": "无限点数和反物质维度升级被禁用，一些无限点里程碑被禁用，并且pent除以点增益，但解锁otf是必要的。",
    "IP Doubler": "无限点倍增器",
    "Negative Infinity Booster": "负无限助推器",
    "Permanently unlocks hex as an otherworldly feature.": "作为超凡脱俗功能永久解锁 hex。",
    "Progress gets softcapped at 1e300 antimatter.": "在1e300反物质的时候，进度达到软上限。",
    "Skip the big crunch screen, and automatically reset.": "跳过大坍缩屏幕，并自动重置。",
    "Unlock new booster dice effects, and booster dice automation": "解锁新的助推器骰子效果，和助推器骰子自动化",
    "Unlock new rocket fuel abilities, and gain 20% of rocket fuel per second.": "解锁新的火箭燃料能力，每秒获得20%的火箭燃料。",
    "Unlock the Otherworldy Feature: Rocket Fuel.": "解锁超凡脱俗功能：火箭燃料",
    "Unlocks a new check back button at level 125.": "在125级解锁一个新的“回访”按钮。",
    "Unlocks the point halter (in portal).": "解锁点数束缚（在传送门）。",
    "Unlocks infinity point buyables and new milestones.": "解锁无限点可购买和新的里程碑。",
    "You are stuck in dice, the booster dice automatically rolls but on every roll, it does a reset equivalent to a big crunch. There are also general debuffs.": "你被困在骰子中，助推器会自动重掷，但每次重掷时，它都会重置，相当于一个大坍缩。也有一般的减益。",
    "BREAK THE BARRIER. KILL TAV.": "突破屏障。杀了Tav。",
    "Buyables and Upgrades": "可购买和升级",
    "corrupted infinities.": "腐化的无限。",
    "shattered infinities.": "破碎的无限。",
    "disfigured infinities.": "损毁的无限。",
    "THE BARRIER": "屏障",
    "negative infinity points.": "负无限点。",
    "Infinities": "无限",
    "(Infinity types are produced on infinity reset.)": "（无限类型在无限重置时产生。）",
    "(You must be in ONLY ONE otherworldy feature to be able to produce as well.)": "（你必须只有在一个超凡脱俗的功能中才能进行生产。）",
    "(You must be in Tav's domain to produce the alternate broken infinity types)": "（你必须在Tav的域中才能产生候补的打破无限类型）",
    "Broken Infinity Multiplier": "打破无限乘数",
    "broken infinities.": "打破无限。",
    "Autobuys dice buyables.": "自动购买骰子可购买。",
    "Autobuys hex buyables (not blessings).": "自动购买hex可购买 (没有祝福).",
    "Auto activates the first four rocket fuel abilities.": "自动激活前四个火箭燃料能力。",
    "Antimatter Dimension Multiplier": "反物质维度乘数",
    "Antidebuff Point Multiplier": "反减益点数乘数",
    "Corrupted": "腐化",
    "Debuffs explained in challenge!": "减益在挑战中解释！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "MrRedShark": "MrRedShark",
    "Cantepocalypse": "Cantepocalypse",
    "v1.1 - The Pet Update Part 1 - With Bugfixes": "v1.1 -宠物更新第1部分-修复错误",
    "Pent": "Pent",
    "Tetr": "Tetr",
    "Cookie": "Cookie",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "AD": "AD",
    "GH": "GH",
    "DE": "DE",
    "CB": "CB",
    "Hex": "Hex",
    "HLT": "HLT",
    "OTF": "OTF",
    "UNI": "UNI",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'On': '打开',
    'ON': '打开',
    'Off': '关闭',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模组树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模组树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Playtime: ": "游戏时长: ",
    "Volume: ": "音量: ",
    "Hotkey Toggle: ": "快捷键切换: ",
    "Music Toggle: ": "音乐切换: ",
    "Offline Production: ": "离线生产: ",
    "Your rank boosts points by x": "你的等级提升点数 x",
    "Your tier boosts points by x": "你的层级提升点数 x",
    "Your tetr boosts points by x": "你的tetr提升点数 x",
    "Total Mult: x": "总乘数: x",
    "Buy Max ": "购买最大 ",
    "Next factor unlocks at tetr ": "下一个因子解锁于 tetr ",
    "Unlocks Factor ": "解锁因子 ",
    "trees, which boost prestige point gain by x": "树，可以提升声望点数增益 x",
    "You will gain ": "你将获得 ",
    "You are making ": "你生成 ",
    "Boosts celestial points based on grass: Currenty: ": "基于草提升天体点数：当前：",
    "Your pent boosts prestige points by ": "你的pent提升声望点数 ",
    "Divides golden grass spawn time by": "除以金草产生时间",
    "Grass value: ": "草价值: ",
    "Golden grass value: ": "金草价值: ",
    "Celestial Points: x": "天体点数: x",
    "Factor Power: ": "因子力量: ",
    "fertilizer, which boosts grass value by x": "肥料，提高草的价值 x",
    "Grass Value: x": "草价值: x",
    "Leaf Gain: x": "树叶增益: x",
    "Prestige Points: x": "声望点数: x",
    "Increases grass capacity based on pent. (Max: ": "基于pent增加草的容量。(上限：",
    "mods, which boost tree gain by x": "模组，提高树的增益 x",
    "(Highest Level: ": "(最高等级: ",
    "Evo Shard Rarity: ": "进化碎片稀有度: ",
    "Unsmith cost: ": "非铁匠成本：",
    "Slax cost: ": "斯莱克斯成本：",
    "Normal Face cost: ": "普通脸成本：",
    "Teste cost: ": "泰斯特成本：",
    "Star cost: ": "星星成本：",
    "THE WATCHING EYE cost: ": "注视之眼成本：",
    "Shark cost: ": "鲨鱼成本：",
    "Gwa cost: ": "Gwa成本：",
    "Egg Guy cost: ": "鸡蛋男成本：",
    "Gd Checkpoint cost: ": "Gd检查点成本：",
    "Unlocks at check back level ": "解锁于回访等级 ",
    "Evolve ": "进化",
    "You gained an Evolution Shard! ": "你获得了一个进化碎片！",
    "Evo shard cost: ": "进化碎片成本：",
    "Code Experience: x": "代码经验：x",
    "Current rolls: ": "当前投掷: ",
    "Currently boosting points. (Currently x": "当前正在提升 点数。(当前 x",
    "Currently boosting prestige points. (Currently x": "当前正在提升 声望点数。(当前 x",
    "Currently boosting grass value. (Currently x": "当前正在提升 草价值。(当前 x",
    "Currently boosting lines of code. (Currently x": "当前正在提升 代码行。(当前 x",
    "Currently boosting fertilizer. (Currently x": "当前正在提升 肥料。(当前 x",
    "Currently boosting mods. (Currently x": "当前正在提升 模组。(当前 x",
    "Currently boosting factor power. (Currently x": "当前正在提升 因子力量。(当前 x",
    "Currently boosting code experience. (Currently x": "当前正在提升 代码经验。(当前 x",
    "Currently boosting leaves. (Currently x": "当前正在提升 树叶。(当前 x",
    "Currently boosting trees. (Currently x": "当前正在提升 树。(当前 x",
    "Currently boosting grasshoppers. (Currently x": "当前正在提升 蚱蜢。(当前 x",
    "Fertilizer: x": "化肥: x",
    "Grasshoppers: x": "蚱蜢: x",
    "Points: x": "点数: x",
    "Mods: x": "模组: x",
    "Trees: x": "树: x",
    "Leaves: x": "树叶: x",
    "Lines of Code: x": "代码行: x",
    "Upgrade (": "升级 (",
    "1st dimension": "第 1 维度",
    "2nd dimension": "第 2 维度",
    "3rd dimension": "第 3 维度",
    "4th dimension": "第 4 维度",
    "5th dimension": "第 5 维度",
    "6th dimension": "第 6 维度",
    "7th dimension": "第 7 维度",
    "8th dimension": "第 8 维度",
    "rocket fuel, which boost grassshoppers by x": "火箭燃料，提升蚱蜢增 x",
    "Next factor unlocks at tier ": "下一个因子解锁于层级 ",
    "Boosts celestial points based on grass: Currently: ": "基于草提升天体点数：当前：",
    "which divide pest gain by /": "除以害虫收益 /",
    "Your chosen effect is boosting points by x": "你选择的效果是提升点数 x",
    "Paragon Shard Rarity: ": "完美碎片稀有度：",
    "Replicanti Mult: ": "复制乘数: ",
    "Time: ": "时间: ",
    "You are stuck in rocket fuel, and point gain is raised to the ": "你被困在火箭燃料中，点数增益上升到 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " Grass (Hover over the grass)": " 草 (鼠标在草上晃动)",
    " IX": " IX",
    " to pet button cooldown.": " 宠物按钮冷却时间。",
    " to xp button cooldown.": " 经验按钮冷却时间。",
    " to all check back button cooldowns.": " 全部回访按钮冷却时间。",
    " to rank requirement.": " 等级要求。",
    " to tetr requirement.": " tetr要求。",
    " to mod requirement.": " 模组要求。",
    " to tree requirement.": " 树要求。",
    " to tier requirement.": " 层级要求。",
    " to check back xp requirement.": " 回访经验要求。",
    " - Spider": " - 蜘蛛",
    " - Blob": " - Blob",
    " - Clock": " - 时钟",
    " - Antimatter": " - 反物质",
    " - Trollface": " - 反物质",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s.$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)m ([\d\.]+)s.$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s.$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^([\d\.]+). \(\+([\d\.,]+)\)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^([\d\.]+)e([\d\.,]+). \(\+([\d\.]+)e([\d\.,]+)\)$/,
    /^([\d\.]+)e([\d\.,]+). \(\+([\d\.]+)e([\d\.,]+)\). $/,
    /^ \(([\d\.]+)x\): ([\d\.,]+) \(\+([\d\.]+)\/s\)    $/,
    /^ \(([\d\.]+)x\): ([\d\.,]+) \(\+([\d\.]+)e([\d\.,]+)\/s\)    $/,
    /^ \(([\d\.]+)x\): ([\d\.]+)e([\d\.,]+) \(\+([\d\.]+)e([\d\.,]+)\/s\)    $/,
    /^ \(([\d\.]+)x\): ([\d\.,]+) \(\+([\d\.,]+)\/s\)    $/,
    /^ \(([\d\.]+)e([\d\.,]+)x\): ([\d\.]+)e([\d\.,]+) \(\+([\d\.]+)e([\d\.,]+)\/s\)    $/,
    /^成本(.+)$/,
    /^\t\-(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^([\d\.,]+). \(\+([\d\.,]+)\). $/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+), ([\d\.,]+).$/,
    /^([\d\.,]+), ([\d\.,]+), ([\d\.,]+).$/,
    /^([\d\.,]+), ([\d\.,]+), ([\d\.,]+)(.+).$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) factor power per second.$/, '你每秒获得 $1 因子力量。'],
    [/^You are rolling a (.+) sided dice.$/, '你在掷一个 $1 面的骰子。'],
    [/^antimatter, which boosts points by (.+) \(based on points and antimatter\)$/, '反物质，提升点数 $1（基于点数和反物质）'],
    [/^You have (.+) negative infinity points. (.+)$/, '你有 $1 负无限点数。$2'],
    [/^You have (.+) infinity points. (.+)$/, '你有 $1 无限点数。$2'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) factor power.$/, '你有 $1 因子力量。'],
    [/^You have (.+) fertilizer.$/, '你有 $1 肥料。'],
    [/^You have ([\d\.]+)e([\d\.,]+)$/, '你有 $1e$2'],
    [/^You have (.+) dice.$/, '你有 $1 骰子。'],
    [/^You have (.+) grass.$/, '你有 $1 草。'],
    [/^You gained a Gwas!$/, '你获得了 一个 Gwas!'],
    [/^You gained (.+) Gwas.$/, '你获得了 $1 Gwas。'],
    [/^You gained (.+) Nova!$/, '你获得了 $1 新星!'],
    [/^You gained (.+) Gwa!$/, '你获得了 $1 Gwas!'],
    [/^You gained (.+) Gd Checkpoints!$/, '你获得了 $1 Gd检查点!'],
    [/^You gained (.+) Unsmiths!$/, '你获得了 $1 非铁匠!'],
    [/^You gained (.+) Teste!$/, '你获得了 $1 泰斯特!'],
    [/^You gained (.+) Slax!$/, '你获得了 $1 斯莱克斯!'],
    [/^You gained (.+) Slaxes!$/, '你获得了 $1 斯莱克斯!'],
    [/^You have (.+) prestige points.$/, '你有 $1 声望点数。'],
    [/^dice points, which boost check back effect by (.+). \(based on dice points\)$/, '骰子点数，这提高了回访效果 $1。（基于骰子点数）'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Teste: (.+) to level up. \(Currently level (.+)\)$/, '泰斯特：$1 以升级。（当前等级 $2）'],
    [/^Gd Checkpoint: (.+) to level up. \(Currently level (.+)\)$/, 'Gd检查点：$1 以升级。（当前等级 $2）'],
    [/^THE WATCHING EYE: (.+) to level up. \(Currently level (.+)\)$/, '注视之眼：$1 以升级。（当前等级 $2）'],
    [/^Normal Face: (.+) to level up. \(Currently level (.+)\)$/, '普通脸：$1 以升级。（当前等级 $2）'],
    [/^Unsmith: (.+) to level up. \(Currently level (.+)\)$/, '非铁匠：$1 以升级。（当前等级 $2）'],
    [/^Slax: (.+) to level up. \(Currently level (.+)\)$/, '斯莱克斯：$1 以升级。（当前等级 $2）'],
    [/^Slax: (.+) to level up \(Currently level (.+)\)$/, '斯莱克斯：$1 以升级（当前等级 $2）'],
    [/^Shark: (.+) to level up. \(Currently level (.+)\)$/, '鲨鱼：$1 以升级。（当前等级 $2）'],
    [/^Star: (.+) to level up. \(Currently level (.+)\)$/, '星星：$1 以升级。（当前等级 $2）'],
    [/^Gwa: (.+) to level up. \(Currently level (.+)\)$/, 'Gwa：$1 以升级。（当前等级 $2）'],
    [/^Egg Guy: (.+) to level up. \(Currently level (.+)\)$/, '鸡蛋男：$1 以升级。（当前等级 $2）'],
    [/^Nova: (.+) to level up. \(Currently level (.+)\)$/, '新星：$1 以升级。（当前等级 $2）'],
    [/^You are level (.+), which boosts celestial point gain by (.+).$/, '你现在是 $1 级，这将使你的天体点数增加 $2。'],
    [/^Increases grass capacity by (.+) and golden grass by (.+).$/, '增加草的容量 $1 和金草 $2。'],
    [/^\(Req: (.+) trees and (.+) celestial points\)$/, '（要求： $1 树和 $2 天体点数）'],
    [/^After (.+) trees, leaf gain is divided by (.+) \(Based on trees\)$/, '$1 棵树后，树叶增益除以 $2（基于树）'],
    [/^Boosts tree and mod gain based on pent: Currenty: (.+) and (.+) respectively.$/, '提升树和模组增益：当前：分别为 $1 和 $2。'],
    [/^Boosts tree and mod gain based on pent: Currently: (.+) and (.+) respectively.$/, '提升树和模组增益：当前：分别为 $1 和 $2。'],
    [/^(.+) Seconds to spawn grass.$/, '$1 秒去产生草。'],
    [/^(.+) Seconds to spawn golden grass.$/, '$1 秒去产生金草。'],
    [/^(.+) Golden grass.$/, '$1 金草。'],
    [/^RF Tree Boost: Gives a (.+) boost to trees. \((.+) left\)$/, '火箭燃料 树提升：给予 $1 树提升。(剩余 $2)'],
    [/^RF Grass Boost: Gives a (.+) boost to grass. \((.+) left\)$/, '火箭燃料 草提升：给予 $1 草提升。(剩余 $2)'],
    [/^RF Point Boost: Gives a (.+) boost to points. \((.+) left\)$/, '火箭燃料 点数提升：给予 $1 点数提升。(剩余 $2)'],
    [/^After (.+) mods, lines of code gain is divided by (.+) \(Based on mods\)$/, '$1 模组后，代码增益行数除以 $2（基于模组）'],
    [/^Next factor unlocks at (.+) prestige points.$/, '下一个因子在 $1 声望点数'],
    [/^Unlocks the next grass factor.\n(.+)Cost: (.+) Fertilizer$/, '解锁下一个草因子。\n$1成本：$2 废料'],
    [/^celestial points \((.+)\/s\).$/, '天体点数 \($1\/秒\)。'],
    [/^which are boosting factor power by (.+).\n(.+)Cost: (.+) Prestige Points$/, '将 因子力量 提升了 $1。\n$2成本：$3 声望点数'],
    [/^which are boosting celestial points by (.+).\n(.+)Cost: (.+) Celestial Points$/, '将 天体点数 提升了 $1。\n$2成本：$3 天体点数'],
    [/^which are boosting lines of code gain by (.+).\n(.+)Cost: (.+) Mods$/, '将代码行增益 提升了 $1。\n$2成本：$3 模组'],
    [/^which are boosting point, factor power, and prestige point gain by (.+).\n(.+)Cost: (.+) Mods$/, '将点数，因子力量和声望点数增益 提升了 $1。\n$2成本：$3 模组'],
    [/^which are boosting code experience gain by (.+).\n(.+)Cost: (.+) Mods$/, '将代码经验增益 提升了 $1。\n$2成本：$3 模组'],
    [/^which are boosting negative infinity point gain by (.+).\n(.+)Cost: (.+) Infinity Points$/, '将负无限点增益 提升了 $1。\n$2成本：$3 无限点'],
    [/^which are multiplying all antimatter dimensions by (.+).\n(.+)Cost: (.+) IP$/, '乘以所有反物质维度 $1。\n$2成本：$3 无限点'],
    [/^which are multiplying all dimension power gain by (.+).\n(.+)Cost: (.+) IP$/, '乘以所有维度力量增益 $1。\n$2成本：$3 无限点'],
    [/^which are multiplying infinity points by (.+).\n(.+)Cost: (.+) IP$/, '乘以无限点 $1。\n$2成本：$3 无限点'],
    [/^which are multiplying negative infinity points by (.+).\n(.+)Cost: (.+) IP$/, '乘以负无限点 $1。\n$2成本：$3 无限点'],
    [/^Which gives (.+) to tickspeed base.\n(.+)Req: (.+) dimensions.$/, '给予 $1 到tick速度基数。\n$2需要：$3 维度。'],
    [/^Which gives (.+) to dimensions.\n(.+)Req: (.+) dimensions.$/, '给予 $1 到维度。\n$2需要：$3 维度。'],
    [/^which are boosting infinity point gain by (.+).\n(.+)Cost: (.+) Negative Infinity Points$/, '将无限点增益 提升了 $1。\n$2成本：$3 负无限点'],
    [/^which are boosting tav essence gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将Tav精华增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting code experience gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将代码经验增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting all antimatter dimension gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将全部反物质维度增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting antimatter effect and gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将反物质效果和增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting grass gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将草增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting grasshop gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将草地增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting point gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将点数增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting tav point gain by (.+).\n(.+)Cost: (.+) Tav Essence$/, '将Tav点数增益 提升了 $1。\n$2成本：$3 Tav精华'],
    [/^which are boosting golden grass value by (.+).\n(.+)Cost: (.+) Mods$/, '将金草价值 提升了 $1。\n$2成本：$3 模组'],
    [/^which are boosting factor power gain by (.+).\n(.+)Cost: (.+) Grass$/, '将因子力量增益 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting celestial point gain by (.+).\n(.+)Cost: (.+) Grass$/, '将天体点数增益 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting celestial point gain by (.+).\n(.+)Cost: (.+) Trees$/, '将天体点数增益 提升了 $1。\n$2成本：$3 树'],
    [/^which are boosting factor power gain by (.+).\n(.+)Cost: (.+) Trees$/, '将因子力量 提升了 $1。\n$2成本：$3 树'],
    [/^which are boosting grass value by (.+).\n(.+)Cost: (.+) Trees$/, '将草价值 提升了 $1。\n$2成本：$3 树'],
    [/^which multiplying check back xp gain by (.+).\n(.+)Cost: (.+) Fertilizer$/, '乘以回访按钮冷却时间 $1。\n$2成本：$3 肥料'],
    [/^which multiplying pet points by (.+).\n(.+)Cost: (.+) Check Back Levels worth of XP.$/, '乘以宠物点数 $1。\n$2成本：$3 回访等级价值的经验。'],
    [/^which multiplying infinity points by (.+).\n(.+)Cost: (.+) Check Back Levels worth of XP.$/, '乘以无限点数 $1。\n$2成本：$3 回访等级价值的经验。'],
    [/^which multiplying XPBoost by (.+).\n(.+)Cost: (.+) Check Back Levels worth of XP.$/, '乘以经验提升 $1。\n$2成本：$3 回访等级价值的经验。'],
    [/^which dividing xp button cooldown by (.+).\n(.+)Cost: (.+) Fertilizer$/, '除以经验按钮冷却时间 $1。\n$2成本：$3 肥料'],
    [/^which are extending mod softcap by (.+).\n(.+)Cost: (.+) Fertilizer$/, '扩展模组软上限 $1。\n$2成本：$3 肥料'],
    [/^which produce (.+) of golden grass value per second.\n(.+)Cost: (.+) Fertilizer$/, '提升 每秒产生 $1 的金草价值。\n$2成本：$3 肥料'],
    [/^which are removing (.+) of the lowest rolls.\n(.+)Cost: (.+) Dice Points$/, '移除 投掷的最低点数 $1。\n$2成本：$3 骰子点数'],
    [/^which are increasing sides on dice by (.+).\n(.+)Cost: (.+) Dice Points$/, '将 骰子面 提升了 $1。\n$2成本：$3 骰子点数'],
    [/^which are boosting dice points by (.+).\n(.+)Cost: (.+) Dice Points$/, '将 骰子点数 提升了 $1。\n$2成本：$3 骰子点数'],
    [/^which are boosting antimatter by (.+).\n(.+)Cost: (.+) Fertilizer$/, '将 反物质 提升了 $1。\n$2成本：$3 肥料'],
    [/^which are boosting antimatter dimensions by (.+).\n(.+)Cost: (.+) Fertilizer$/, '将 反物质维度 提升了 $1。\n$2成本：$3 肥料'],
    [/^which are boosting leaf gain by (.+).\n(.+)Cost: (.+) Fertilizer$/, '将 树叶增益 提升了 $1。\n$2成本：$3 肥料'],
    [/^which are boosting grass value by (.+).\n(.+)Cost: (.+) Fertilizer$/, '将草价值 提升了 $1。\n$2成本：$3 肥料'],
    [/^which are boosting golden grass value by (.+).\n(.+)Cost: (.+) Trees$/, '将金草价值 提升了 $1。\n$2成本：$3 树'],
    [/^which are boosting prestige point gain by (.+).\n(.+)Cost: (.+) Grass$/, '将声望点数增益 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting tree gain by (.+).\n(.+)Cost: (.+) Grass$/, '将 树增益 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting grass value by (.+).\n(.+)Cost: (.+) Grass$/, '将 草价值 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting golden grass value by (.+).\n(.+)Cost: (.+) Grass$/, '将 金草价值 提升了 $1。\n$2成本：$3 草'],
    [/^which are boosting leaf gain by (.+).\n(.+)Cost: (.+) Trees$/, '将 树叶增益 提升了 $1。\n$2成本：$3 树'],
    [/^which are producing (.+) leaves per second.\n(.+)Cost: (.+) Prestige Points$/, '每秒生产 $1 树叶。\n$2成本：$3 声望点数'],
    [/^which are extending the tree softcap by (.+).\n(.+)Cost: (.+) Prestige Points$/, '扩展树的软上限 $1。\n$2成本：$3 声望点数'],
    [/^which are extending tree softcap by (.+).\n(.+)Cost: (.+) Fertilizer$/, '扩展树的软上限 $1。\n$2成本：$3 肥料'],
    [/^which produce (.+) of grass value per second.\n(.+)Cost: (.+) Fertilizer$/, '每秒生产 $1 的草价值。\n$2成本：$3 肥料'],
    [/^which produce (.+) of prestige points per second.\n(.+)Cost: (.+) Fertilizer$/, '每秒生产 $1 的声望点数。\n$2成本：$3 肥料'],
    [/^which add (.+) to the factor effect base.\n(.+)Cost: (.+) Fertilizer$/, '给因子效应基数增加 $1。\n$2成本：$3 肥料'],
    [/^which are dividing the tree requirement by (.+).\n(.+)Cost: (.+) Trees$/, '除以 树 需求 $1。\n$2成本：$3 树'],
    [/^which are dividing pent requirement by (.+).\n(.+)Cost: (.+) Golden Grass$/, '除以 pent 需求 $1。\n$2成本：$3 金草'],
    [/^which are dividing golden grass time requirement by (.+).\n(.+)Cost: (.+) Fertilizer$/, '除以 黄金草 时间需求 $1。\n$2成本：$3 肥料'],
    [/^which are increasing golden grass capacity by (.+).\n(.+)Cost: (.+) Golden Grass$/, '增加金草容量 $1。\n$2成本：$3 金草'],
    [/^which are increasing grass capacity by (.+).\n(.+)Cost: (.+) Grass$/, '增加草容量 $1。\n$2成本：$3 草'],
    [/^which are dividing grass time requirement by (.+).\n(.+)Cost: (.+) Grass$/, '除以 草时间需求 $1。\n$2成本：$3 草'],
    [/^Buys another dice.\n(.+)Cost: (.+) Dice Points$/, '购买另一个骰子。\n$1成本：$2 骰子点数'],
    [/^Buys another dice.\n(.+)Req: (.+) Dice Points$/, '购买另一个骰子。\n$1需要：$2 骰子点数'],
    [/^Automatically rolls the dice every (.+) seconds.\n(.+)Cost: (.+) Dice Points$/, '每 $1 秒自动掷一次骰子。\n$2成本：$3 骰子点数'],
    [/^which boost celestial points by (.+).$/, '提升天体点数 $1。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/([\d\.,]+) Antimatter Galaxies$/, '$1\/$2 反物质星系'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) prestige points$/, '$1e$2 声望点数'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) celestial points$/, '$1e$2 天体点数'],
    [/^([\d\.]+) Infinities$/, '$1 无限'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) Infinity$/, '$1 无限'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Antimatter Galaxies$/, '$1 反物质星系'],
    [/^([\d\.,]+) Antimatter Boosts$/, '$1 反物质提升'],
    [/^([\d\.,]+) Dimension Boosts$/, '$1 维度提升'],
    [/^You will unlock something at level ([\d\.,]+)!$/, '你将解锁新内容在等级 $1！'],
    [/^You will unlock something at level ([\d\.,]+)! \(Pet shop\)$/, '你将解锁新内容在等级 $1！（宠物商店）'],
    [/^You have ([\d\.,]+)$/, '你有 $1'],
    [/^Universe ([\d\.,]+)$/, '宇宙 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Pent ([\d\.,]+)$/, 'Pent $1'],
    [/^Row ([\d\.,]+)$/, '行 $1'],
    [/^Crate ([\d\.,]+)$/, '箱子 $1'],
    [/^Crate ([\d\.,]+) cost: ([\d\.,]+)$/, '箱子 $1 成本 $2'],
    [/^Buy Crate ([\d\.,]+)$/, '购买箱子 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\+(.+) Pet Points.$/, '\+$1 宠物点数。'],
    [/^\+(.+) DP.$/, '\+$1 骰子点数。'],
    [/^\+(.+) XP.$/, '\+$1 经验值。'],
    [/^\+(.+) base coin dust gain per hour.$/, '\+$1 每小时获得的基本硬币尘埃。'],
    [/^\/(.+) golden grass spawn time.$/, '\/$1 金草产生时间。'],
    [/^\+(.+) to the effect.$/, '\+$1 到效果。'],
    [/^\^(.+) to celestial point gain.$/, 'x$1 到 天体点数增益。'],
    [/^\^(.+) to prestige point gain.$/, 'x$1 到 声望点数增益。'],
    [/^\^(.+) to grasshopper gain.$/, 'x$1 到 蚱蜢增益。'],
    [/^\^(.+) to code experience gain.$/, 'x$1 到 代码经验增益。'],
    [/^\^(.+) to leaf gain.$/, 'x$1 到 树叶增益。'],
    [/^\^(.+) to tree gain.$/, 'x$1 到 树增益。'],
    [/^\^(.+) to grass gain.$/, 'x$1 到 草增益。'],
    [/^\^(.+) to unsmith effect.$/, 'x$1 到 非铁匠效果。'],
    [/^\^(.+) to all antimatter dimensions.$/, 'x$1 到 全部反物质维度。'],
    [/^x(.+) to points.$/, 'x$1 到 点数。'],
    [/^x(.+) to check back xp$/, 'x$1 到 回访经验'],
    [/^x(.+) to check back xp \(based on check back level\)$/, 'x$1 到 回访经验（基于回访等级）'],
    [/^x(.+) to check back xp.$/, 'x$1 到 回访经验。'],
    [/^x(.+) to code experience.$/, 'x$1 到 代码经验。'],
    [/^x(.+) to fertilizer \(based on grass\).$/, 'x$1 到 肥料 (基于草)。'],
    [/^x(.+) to fertilizer.$/, 'x$1 到 肥料。'],
    [/^x(.+) to golden grass.$/, 'x$1 到 金草。'],
    [/^x(.+) to antimatter.$/, 'x$1 到 反物质。'],
    [/^x(.+) to dice points \(based on highest combo\).$/, 'x$1 骰子点数（基于最高组合）。'],
    [/^x(.+) to to antimatter dimensions \(based on infinities\).$/, 'x$1 到 反物质维度（基于无限）。'],
    [/^x(.+) to to grasshoppers \(based on evo shards\).$/, 'x$1 到 蚱蜢（基于进化碎片）。'],
    [/^x(.+) to to rocket fuel \(based on pet points\).$/, 'x$1 到 火箭燃料（基于宠物点数）。'],
    [/^x(.+) to to mods \(based on dice points\).$/, 'x$1 到 模组（基于骰子点数）。'],
    [/^x(.+) to grasshoppers.$/, 'x$1 到 蚱蜢。'],
    [/^x(.+) to grass value.$/, 'x$1 到 草价值。'],
    [/^x(.+) to mod gain.$/, 'x$1 到 模组增益。'],
    [/^x(.+) to golden grass value.$/, 'x$1 到 金草价值。'],
    [/^x(.+) to factor power.$/, 'x$1 到 因子力量。'],
    [/^x(.+) to leaves.$/, 'x$1 到 树叶。'],
    [/^x(.+) to lines of code.$/, 'x$1 到 代码行。'],
    [/^x(.+) to tree gain.$/, 'x$1 到 树增益。'],
    [/^x(.+) to XPBoost.$/, 'x$1 到 经验提升。'],
    [/^x(.+) to prestige points.$/, 'x$1 到 声望点数。'],
    [/^x(.+) to dimensions.$/, 'x$1 到 维度。'],
    [/^x(.+) to 1st dimensions.$/, 'x$1 到 第 1 维度。'],
    [/^x(.+) to 2nd dimensions.$/, 'x$1 到 第 2 维度。'],
    [/^x(.+) to 3rd dimensions.$/, 'x$1 到 第 3 维度。'],
    [/^x(.+) to ([\d\.,]+)th dimensions.$/, 'x$1 到 第 $2 维度。'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+) of each alternate broken infinity type.$/, '$1 每一种候补破碎无限类型'],
    [/^(.+) Drippy Ufo$/, '$1 水滴状UFO'],
    [/^(.+) Highest Dice Pet Combo$/, '$1 最高骰子宠物组合'],
    [/^(.+) Normal Face$/, '$1 普通脸'],
    [/^(.+) Shark$/, '$1 鲨鱼'],
    [/^(.+) Evo Shard$/, '$1 进化碎片'],
    [/^(.+) Goofy Ahh Thing$/, '$1 高飞东西'],
    [/^(.+) Shark Level$/, '$1 鲨鱼等级'],
    [/^(.+) Egg Guy$/, '$1 鸡蛋男'],
    [/^(.+) Gd Checkpoint$/, '$1 Gd检查点'],
    [/^(.+) Unsmith$/, '$1 非铁匠'],
    [/^(.+) Unsmith Level$/, '$1 非铁匠等级'],
    [/^(.+) Slax$/, '$1 斯莱克斯'],
    [/^(.+) Nova$/, '$1 新星'],
    [/^(.+) Gwa$/, '$1 Gwa'],
    [/^(.+) Star$/, '$1 星星'],
    [/^(.+) Evolution Shards$/, '$1 进化碎片'],
    [/^(.+) Teste$/, '$1 泰斯特'],
    [/^(.+) THE WATCHING EYE$/, '$1 注视之眼'],
    [/^(.+)x to dimensions \(x(.+).\)$/, '$1x 到维度 \(x$2.\)'],
    [/^Cost: (.+) Prestige Points$/, '成本：$1 声望点数'],
    [/^Cost: (.+) Celestial Points$/, '成本：$1 天体点数'],
    [/^Cost: (.+) Infinity Points$/, '成本：$1 无限点数'],
    [/^Cost: (.+) Antimatter$/, '成本：$1 反物质'],
    [/^Cost: (.+) AM$/, '成本：$1 反物质维度'],
    [/^Tickspeed Cost: (.+) AM.$/, 'Tick速度 成本：$1 反物质维度。'],
    [/^Cost: (.+) Tav Essence$/, '成本：$1 Tav精华'],
    [/^Cost: (.+) Grass$/, '成本：$1 草'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Corrupted Infinities$/, '成本：$1 腐化的无限'],
    [/^Cost: (.+) Shattered Infinities$/, '成本：$1 破碎的无限'],
    [/^Cost: (.+) Disfigured Infinities$/, '成本：$1 损毁的无限'],
    [/^Cost: (.+) Rocket Fuel$/, '成本：$1 火箭燃料'],
    [/^\(Req: (.+) Grass and (.+) Celestial Points\)$/, '\(要求：$1 草 和 $2 天体点数\)'],
    [/^\(Req: (.+) Celestial Points\)$/, '\(要求：$1 天体点数\)'],
    [/^Autoroll: (.+)s$/, '自动投掷：$1秒'],
    [/^Req: (.+) points$/, '要求：$1 点数'],
    [/^Req: (.+) Tier$/, '要求：$1 层级'],
    [/^Req: (.+) Points$/, '要求：$1 点数'],
    [/^Req: (.+) Rank$/, '要求：$1 等级'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) ([\d\.,]+)th dimensions.$/, '要求：$1 第 $2 维度'],
    [/^Req: (.+) ([\d\.,]+)th dimensions. (.+) to tickspeed base.$/, '要求：$1 第 $2 维度. $3 to tick速度基数.'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);